version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
    - 8080:8080
