version: "3"

services:
  db:
    image: mysql
    container_name: mysql_test
    command: --default-authentication-plugin=mysql_native_password --sql-mode=''
    restart: always
    environment:
      MYSQL_USER: new_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: profile_test_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-db:
