version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql_prod
    command: --default-authentication-plugin=mysql_native_password --sql-mode=''
    restart: always
    environment:
      MYSQL_USER: new_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: profile_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app-net
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --password=my-secret-pw
      interval: 10s
      timeout: 2s
      retries: 10
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    image: gcr.io/profile-api-299602/profile-api:latest
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    container_name: profile-api
    command: bash -c "npm run setup && npm start serve"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    networks:
      - app-net
volumes:
  my-db:

networks:
  app-net:
    driver: bridge
