swagger: "2.0"
info:
  title: Profile API
  description: Profile API
  version: 1.0.0
host: localhost
basePath: /api
schemes:
  - https
paths:
  /profiles:
    get:
      summary: Returns a list of profiles
      operationId: getProfiles
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                profileContent:
                  type: object
                  properties:
                    summary:
                      type: string
                    achievements:
                      type: string
                    skills:
                      type: string
                contactDetails:
                  type: object
                  properties:
                    email:
                      type: string
                    phoneNumber:
                      type: string
                socialContent:
                  type: array
                  items:
                    type: string
                imageUrl:
                  type: string
                cvUrl:
                  type: string
  /profile/{profileId}:
    get:
      summary: Gets a profile by id
      operationId: getProfileById
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              name:
                type: string
              profileContent:
                type: object
                properties:
                  summary:
                    type: string
                  achievements:
                    type: string
                  skills:
                    type: string
              contactDetails:
                type: object
                properties:
                  email:
                    type: string
                  phoneNumber:
                    type: string
              socialContent:
                type: array
                items:
                  type: string
              imageUrl:
                type: string
              cvUrl:
                type: string
  /profile:
    put:
      summary: Add a new profile resource
      operationId: create
      consumes:
        - application/json
      parameters:
        - in: body
          name: profile
          description: the profile to create
          schema:
            type: object
            required:
              - name
              - image
              - profileContent
              - contactDetails
            properties:
              name:
                type: string
                properties:
                  url:
                    type: string
              profileContent:
                required:
                  - summary
                  - achievements
                  - skills
                type: object
                properties:
                  summary:
                    type: string
                  achievements:
                    type: string
                  skills:
                    type: string
              contactDetails:
                required:
                  - email
                  - phoneNumber
                type: object
                properties:
                  email:
                    type: string
                  phoneNumber:
                    type: string
              socialContent:
                type: array
                items:
                  type: string
              imageUrl:
                type: string
              cvUrl:
                type: string
      responses:
        '201':
          description: created profile successfully
          schema:
            type: object
            properties:
              id:
                type: integer







